### ISSUE TITLE
Scroll in Android is not working

### ISSUE THREAD

**Issue by nosov-vitaliy** [sc12070/react-native-drag-sort-gridview#2]
Thanks for cute component, I have a problem to scroll items in android. Scroll is not working (nothing happened on scrolling)

**Comment by nosov-vitaliy** [comment]
Hello, I tried your example from your GitHub repository. I can see scroll in android now. But there is a situation, when I try quick re-arrange elements and it is stuck and not move more

I recorded a video

https://github.com/sc12070/react-native-drag-sort-gridview/assets/5630611/b8c54a31-4359-4bc5-9e3b-bedd65eaed00

**Comment by sc12070** [comment]
> Hello, I tried your example from your GitHub repository. I can see scroll in android now. But there is a situation, when I try quick re-arrange elements and it is stuck and not move more
> 
> I recorded a video
> 

Thanks for reporting this issue. It had been fixed in v1.4.2.

**Comment by damienborgniet** [comment]
I'm using 1.5.0 and still the same problem. Impossible to scroll. A solution will be to edit order only if onLongPress on element, it's possible ?
